{% set name = "protobuf" %}
{% set version = "3.1.0" %}
{% set version_str = "v3.1.0" %}
{% set sha256 = "0a0ae63cbffc274efb573bdde9a253e3f32e458c41261df51c5dbc5ad541e8f7" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/google/protobuf/archive/{{ version_str }}/{{ name }}-{{ version_str }}.tar.gz
    sha256: {{ sha256 }}
    patches:

build:
    number: 0
    features:
        - vc9                # [win and py27]
        - vc10               # [win and py34]
        - vc14               # [win and py35]

requirements:
    build:
        - git
        - cmake              # [win]
        - autoconf           # [unix]
        - automake           # [unix]
        - libtool            # [unix]
        - pkg-config         # [unix]
        - zlib 1.2.*
        - python
        - setuptools
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]

    run:
        - zlib 1.2.*
        - python
        - setuptools
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]

test:
    commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
        - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
        - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]

    imports:
        - google
        - google.protobuf
        - google.protobuf.internal
        - google.protobuf.pyext

about:
    home: https://developers.google.com/protocol-buffers/
    license: New BSD License
    summary: Protocol Buffers - Google's data interchange format

extra:
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - jjhelmus
        - ocefpaf
