{% set version = "2.6.1" %}

package:
    name: protobuf
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/google/protobuf/releases/download/v{{ version }}/protobuf-{{ version }}.tar.gz
    md5: f3916ce13b7fcb3072a1fa8cf02b2423
    patches:
        - configure.patch

build:
    number: 0
    skip: true  # [win or py3k]

requirements:
    build:
        - autoconf
        - automake
        - libtool
        - pkg-config
        - python
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]
        - google-apputils

    run:
        - python
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]
        - google-apputils

test:
    commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf.a                # [unix]
        - test -f ${PREFIX}/lib/libprotobuf.dylib            # [osx]
        - test -f ${PREFIX}/lib/libprotobuf.so               # [linux]

    imports:
        - google
        - google.protobuf
        - google.protobuf.compiler
        - google.protobuf.internal
        - google.protobuf.pyext

about:
    home: https://developers.google.com/protocol-buffers/
    license: New BSD License
    summary: Protocol Buffers - Google's data interchange format

extra:
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - jjhelmus
        - ocefpaf
