appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GaueNIMPQWkKDIJSwEbiSeivKu0gUA249HprxJRhFuQl0xcy6Y+MB3F1z/aJoC4gVtpcekxqaHw18cVOh0qwCp1VxhFC6Wa48jRX+fqlIQWGNAQEeJXDRWE2zuTB66GbTt3W7vh+19HPNIEQODL9gzrfPx/scuYh4EyIPku8TzWC9LosY53voF7OGOU6khiNxq/yWNR7eA1q4NwZr85GZ174f7N2GaA0Xq+xDSo5k7ZytF03QJywUn75UFKvw5p9eWQJ7BsLQjXzAvMZv7TwWcf3CG5rH6tMlXFd33znKVQDWI3arzNakyzDtZvv9dJ/sM5MrwGi68/Op8HPyUQlwJkeJghFmHTxEB8VSc+VVByz058dakyHi4sOfytXCDNSDgjiWXBUNmMDhnFxRPyywghlEmo0hb2nh8c8A9PkB+PiNP5j771pSSuagFx+TiRxhwtQre+/QAEgOnzlseS2eqNMxYwH2udpjC5cHA00ZOJPKmFNJSTIbQWA8y5gkJN7TQXEIQe6AmACmr+gdWhg9u35Rle1u1mLeFhGgjosz38aKXXk69Rz/V0obIgWzOXwZFcFEvVg1xWf2ZDkR1fQ6nitZlP4Rp2zdYeE794VdPylT0MHr/8rsUBVd3SwrJ8Hiofk2//1n71ZJaKAntfbcpqS1mbnicifCMAOo0wIbys=}
provider:
  win: azure
